# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bottachable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='media_type',
            field=models.CharField(choices=[('picture', 'Picture'), ('video', 'Video'), (None, 'No media')], default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
